default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: taximatico_development

test: &test
  <<: *default
  database: taximatico_text

production:
  <<: *default
  database: taximatico_production

cucumber:
  <<: *test

<%= IO.read("#{Rails.root}/config/database.local.yml") if File.exists?("#{Rails.root}/config/database.local.yml") %>
