# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e70cddb3c8c9fce8ed63bd1633f02c79c3f27b460e55af8f11de83056a651b8bf5233274739c97202c95e21af11def0c108ac7421029238ac69599e1e37ffc27
  twilio_account_sid: ACb76077918871ccf7287d56d4aea12ecd
  twilio_auth_token: f4b7082acfc5648255f252b8a2d2ac70
  twilio_number: +15005550006

test:
  secret_key_base: 411684f885db183c30532ba1dab33d614655b0241fc7ea099b2ae796dd61fead84ac87060ccbafb63b44785d81ff97b4b4ae627d070eaaa64dfc99c69c903230
  twilio_account_sid: ACb76077918871ccf7287d56d4aea12ecd
  twilio_auth_token: f4b7082acfc5648255f252b8a2d2ac70
  twilio_number: +15005550006

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twilio_account_sid: <%= ENV["TWILIO_ACCOUNT_SID"] %>
  twilio_auth_token: <%= ENV["TWILIO_AUTH_TOKEN"] %>
  twilio_number: <%= ENV["TWILIO_NUMBER"] %>

